# https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

sudo: required

services:
  - docker

script:
  - bash ./build.sh

env:
  - tag=1.21.2
  - tag=1.20.4
  - tag=1.19.8
  - tag=1.18.16
  - tag=1.17.17
  - tag=1.16.15
