# https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

sudo: required

services:
  - docker

script:
  - bash ./build.sh

env:
  - tag=1.19.8
  - tag=1.18.9
  - tag=1.17.12
  - tag=1.16.15
  - tag=1.15.12
